# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiga_contrib_letschat', '0002_auto_20150921_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='letschathook',
            name='notify_epic_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letschathook',
            name='notify_epic_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letschathook',
            name='notify_epic_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letschathook',
            name='notify_relateduserstory_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='letschathook',
            name='notify_relateduserstory_delete',
            field=models.BooleanField(default=True),
        ),
    ]
